# Generated by Django 4.1 on 2022-09-21 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Editor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('mail', models.EmailField(max_length=254)),
                ('cantIdeas', models.IntegerField(default=0)),
                ('edad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ideas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(max_length=30)),
                ('texto', models.CharField(max_length=280)),
                ('cantVals', models.IntegerField(default=0)),
                ('puntos', models.IntegerField(default=0)),
                ('datetimePubl', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Lector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('mail', models.EmailField(max_length=254)),
                ('cantVals', models.IntegerField(default=0)),
                ('edad', models.IntegerField()),
            ],
        ),
    ]
