# Generated by Django 4.1 on 2022-09-21 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ideas',
            name='autor',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
